
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Apr 21 16:56:35 EET 2012
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NE = 16;
  public static final int ELSE = 31;
  public static final int CLASS = 29;
  public static final int INT = 22;
  public static final int LP = 20;
  public static final int WHILE = 27;
  public static final int LO = 13;
  public static final int RP = 21;
  public static final int RETURN = 28;
  public static final int IF = 30;
  public static final int ID = 10;
  public static final int STATIC = 26;
  public static final int AO = 18;
  public static final int FA = 11;
  public static final int DO = 6;
  public static final int LB = 12;
  public static final int ST = 8;
  public static final int BOOLEAN = 24;
  public static final int LA = 14;
  public static final int STRING = 25;
  public static final int RB = 19;
  public static final int MO = 4;
  public static final int FLOAT = 23;
  public static final int PO = 3;
  public static final int EOF = 0;
  public static final int SM = 2;
  public static final int error = 1;
  public static final int MD = 17;
  public static final int EQ = 15;
  public static final int BL = 7;
  public static final int NM = 9;
  public static final int TO = 5;
}

