
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 09 20:25:39 EET 2012
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NE = 12;
  public static final int ELSE = 23;
  public static final int CLASS = 21;
  public static final int INT = 25;
  public static final int LP = 16;
  public static final int WHILE = 19;
  public static final int LO = 9;
  public static final int RP = 17;
  public static final int RETURN = 20;
  public static final int IF = 22;
  public static final int ID = 24;
  public static final int STATIC = 18;
  public static final int AO = 14;
  public static final int FA = 7;
  public static final int ST = 29;
  public static final int DO = 6;
  public static final int LB = 8;
  public static final int BOOLEAN = 27;
  public static final int LA = 10;
  public static final int STRING = 28;
  public static final int RB = 15;
  public static final int MO = 4;
  public static final int FLOAT = 26;
  public static final int PO = 3;
  public static final int EOF = 0;
  public static final int SM = 2;
  public static final int error = 1;
  public static final int EQ = 11;
  public static final int MD = 13;
  public static final int BL = 31;
  public static final int NM = 30;
  public static final int TO = 5;
}

