
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 11 12:42:49 EET 2012
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NE = 16;
  public static final int ELSE = 27;
  public static final int CLASS = 25;
  public static final int INT = 5;
  public static final int LP = 20;
  public static final int WHILE = 23;
  public static final int LO = 13;
  public static final int RP = 21;
  public static final int RETURN = 24;
  public static final int IF = 26;
  public static final int ID = 28;
  public static final int STATIC = 22;
  public static final int AO = 18;
  public static final int FA = 11;
  public static final int ST = 29;
  public static final int DO = 10;
  public static final int LB = 12;
  public static final int LA = 14;
  public static final int BOOLEAN = 7;
  public static final int RB = 19;
  public static final int STRING = 8;
  public static final int MO = 4;
  public static final int FLOAT = 6;
  public static final int PO = 3;
  public static final int EOF = 0;
  public static final int SM = 2;
  public static final int error = 1;
  public static final int MD = 17;
  public static final int EQ = 15;
  public static final int BL = 31;
  public static final int NM = 30;
  public static final int TO = 9;
}

